name: yookassa_payments_flutter
description: This Flutter SDK allows processing payments using a payment token. It
  works as an addition to the YooMoney API.
version: 1.5.0
homepage: https://git.yoomoney.ru/projects/SDK/repos/yookassa-payments-flutter-sdk/browse
repository: https://git.yoomoney.ru/projects/SDK/repos/yookassa-payments-flutter-sdk/browse
environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.10.5"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "^4.0.0"
flutter:
  plugin:
    platforms:
      android:
        package: ru.yoomoney.sdk.kassa.payments.flutter
        pluginClass: YookassaPaymentsFlutterPlugin
      ios:
        pluginClass: YookassaPaymentsFlutterPlugin
